/*
	SCRIPT SQL PARA CRIAÇÃO 
	DA TABELA DE CLIENTES
*/
CREATE TABLE CLIENT(
	ID			UNIQUEIDENTIFIER	PRIMARY KEY,
	NAME		VARCHAR(150)		NOT NULL,
	EMAIL		VARCHAR(50)			NOT NULL,
	BIRTHDATE	DATE				NOT NULL);

-- CADASTRANDO CLIENTES
INSERT INTO CLIENT(ID, NAME, EMAIL, BIRTHDATE)
	VALUES
		(NEWID(), 'Ana Maria', 'anamaria@gmail.com', '2000-01-15'),
		(NEWID(), 'João Pedro', 'joaopedro@bol.com', '2005-04-10');

-- CONSULTANDO OS CLIENTES (EM ORDEM ALFABÉTICA)
SELECT ID, NAME, EMAIL, BIRTHDATE
FROM CLIENT
ORDER BY NAME;


